from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "elastic"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs="certs/ca/ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD),
)

# Successful response!
response = client.search(
    index="kibana_sample_data_ecommerce",
    query={
        "bool": {
            "must": [
                {"range": {"taxful_total_price": {"lte": 100}}},
                {"term": {"geoip.city_name": "Birmingham"}},
            ]
        }
    },
    aggregations={"cities": {"terms": {"field": "customer_id"}}},
    size=5,
)

print(response)
